# Site settings
title: "Anthony hengy"
description: "CV Anthony hengy"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Anthony Hengy"
resume_title:                   "Ingenieur logiciel"

# used for the contact button in _layouts/resume.html
resume_contact_email:           ""

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "test"
resume_contact_address:         ""

resume_header_contact_info:     "<span>Antibes</span><br/> <span>Français (natif) - Anglais (pro) </span> "
display_header_contact_info:    "true"

resume_header_intro: "<p>Depuis plusieurs années, je travaille sur des projets où l’automatisation, la fiabilité et la qualité du code sont essentielles. En lien direct avec les équipes métiers et les clients, j’ai développé une communication claire et orientée solution. Mon objectif est de comprendre où je peux concrètement apporter de la valeur, que ce soit sur les outils, les process ou la culture d’équipe.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        ""

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dat-Antho"
  resume_linkedin_url:          "https://www.linkedin.com/in/anthony-hengy"
  resume_website_url:           "https://anthonyhengy.fr"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
